[package]
name = "tests_common"
description = "Common code for integration tests"
edition = "2021"
version = "1.0.0"

[dependencies]
assert_cmd = "2.0"
assert_fs = "1.0"
flate2 = "1.0"
predicates = "3.0"
zip = { version = "0.6", default-features = false, features = ["deflate"] }
