[package]
name = "tests_common"
description = "Common code for integration tests"
edition = "2021"
version = "0.1.0"

[dependencies]
assert_cmd = "2.0.5"
assert_fs = "1.0.10"
predicates = "2.1.1"
zip = { version = "0.6.3", default-features = false, features = ["deflate"] }
